version: '3'

services:
  app-web:
    environment:
      - VIRTUAL_HOST=${WEB_VIRTUAL_HOST}
    build:
      context: build
      dockerfile: nginx.Dockerfile
    volumes:
      - ${PROJECT_PUBLIC_PATH}:/app/public
  app-php:
    environment:
      - APP_ENV
      - APP_DEBUG
      - APP_KEY
      - APP_TIMEZONE
      - LOG_CHANNEL
      - LOG_SLACK_WEBHOOK_URL
      - DB_CONNECTION
      - DB_HOST
      - DB_PORT
      - DB_DATABASE
      - DB_USERNAME
      - DB_PASSWORD
      - CACHE_DRIVER
      - QUEUE_DRIVER
      - SESSION_DRIVER
    build:
      context: build
      dockerfile: php.Dockerfile
    volumes:
      - ${PROJECT_PATH}:/app
